### ISSUE TITLE
[pyteleloisirs.pyteleloisirs] Could not determine URL for N/A / 

### ISSUE THREAD

**Issue by anthosz** [pschmitt/pyteleloisirs#1]
Hello,

Since I have upgraded homeassistant, I have these entries in logs:
Oct 22 14:28:58 xx hass[xx]: 2017-10-22 14:28:58 ERROR (Thread-5) [pyteleloisirs.pyteleloisirs] Could not determine URL for N/A
Oct 22 14:28:58 xx hass[xx]: 2017-10-22 14:28:58 WARNING (Thread-5) [pyteleloisirs.pyteleloisirs] Could not retrieve TV program for N/A

But the idea of pyteleloisirs seems interesting, could you update README so we can use it?

**Comment by pschmitt** [comment]
Yeah, these log entries you are seeing are perfectly normal.
Your livebox play is probably not currently displaying TV, ergo there is no channel info. Therefore there is no programm info that pyteleloisirs can fetch.
I'll issue a PR to homeassistant soon that will fix this among other things. Stay tuned.

EDIT: Regarding usage information please refer to [bin/teleloisirs](https://github.com/pschmitt/pyteleloisirs/blob/master/bin/teleloisirs)

**Comment by pschmitt** [comment]
@anthosz You can checkout said work by placing the [file here](https://github.com/pschmitt/home-assistant/blob/livebox-play-tv-enhancements/homeassistant/components/media_player/liveboxplaytv.py) to `$HASS_CONFIG_DIR/custom_components/media_player/liveboxplaytv.py`

As a bonus you'll get thumbnails from teleloisirs right in your hass GUI.

![Imgur](https://i.imgur.com/031pj8C.png)

**Comment by anthosz** [comment]
Perfect, thank's!

**Comment by pschmitt** [comment]
https://github.com/home-assistant/home-assistant/pull/10033
